# Generated by Django 3.1.3 on 2020-11-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtInfoDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('Vrate', models.CharField(max_length=50, null=True)),
                ('artinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='subapp.artinfodb')),
            ],
        ),
        migrations.CreateModel(
            name='FestivalDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('artinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival', to='subapp.artinfodb')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWorkDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.CharField(max_length=10)),
                ('artinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='subapp.artinfodb')),
            ],
        ),
    ]
