# Generated by Django 3.1.3 on 2020-11-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
    ]
