# Generated by Django 3.1.3 on 2020-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('region', models.CharField(max_length=10)),
                ('image_url', models.TextField(null=True)),
                ('allsum', models.IntegerField()),
                ('kids_m', models.IntegerField()),
                ('ten_m', models.IntegerField()),
                ('twenty_m', models.IntegerField()),
                ('thirty_m', models.IntegerField()),
                ('forty_m', models.IntegerField()),
                ('fifty_m', models.IntegerField()),
                ('old_m', models.IntegerField()),
                ('kids_w', models.IntegerField()),
                ('ten_w', models.IntegerField()),
                ('twenty_w', models.IntegerField()),
                ('thirty_w', models.IntegerField()),
                ('forty_w', models.IntegerField()),
                ('fifty_w', models.IntegerField()),
                ('old_w', models.IntegerField()),
            ],
        ),
    ]
